### ISSUE TITLE
Docker erlerobot/gym-gazebo no display.

### ISSUE THREAD

**Issue by wajeehulhassanvii** [AcutronicRobotics/gym-gazebo2#12]
Hi there! Sorry to bother you. I am trying to run Erlecopter from this repository https://github.com/erlerobot/gym-gazebo#usage with Docker. I'm following the steps but gazebo is not being displayed when I am issuing the command gzclient in another terminal.
The error log is below, I'm getting this in my terminal verbose after I run the erlecopter program.

Your help would be appreciated.

> [2019-04-04 05:25:02,940] Making new env: GazeboErleCopterHover-v0
> /usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
>   warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
> 
> ##############################################################################
> Load Erle-Copter parameters in MavProxy console (sim_vehicle.sh):
> 
> MAV> param load /usr/local/gym/gym-gazebo/gym_gazebo/envs/installation/../assets/params/Erle-Copter.param
> 
> Then, press <Enter> here to launch Gazebo...
> 
> ##############################################################################Warning: This program is an suid-root program or is being run by the root user.
> The full text of the error or warning message cannot be safely formatted
> in this environment. You may get a more descriptive message by running the
> program as a non-root user or by removing the suid bit on the executable.
> xterm: Xt error: Can't open display: %s
> xterm: DISPLAY is not set
> 
> Roscore launched!
> Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
> ... logging to /root/.ros/log/06019c26-569a-11e9-a579-0242ac110003/roslaunch-adcf198a9e82-566.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://adcf198a9e82:43213/
> ros_comm version 1.11.20
> 
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /rosdistro: indigo
>  * /rosversion: 1.11.20
> 
> NODES
> 
> auto-starting new master
> process[master]: started with pid [580]
> ROS_MASTER_URI=http://adcf198a9e82:11311/
> 
> setting /run_id to 06019c26-569a-11e9-a579-0242ac110003
> Gazebo launched!
> Taking off in in 10s
> ... logging to /root/.ros/log/06019c26-569a-11e9-a579-0242ac110003/roslaunch-adcf198a9e82-598.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> process[rosout-1]: started with pid [607]
> started core service [/rosout]
> Taking off in in 9s
> Taking off in in 8s
> started roslaunch server http://adcf198a9e82:43087/
> 
> SUMMARY
> ========
> 
> CLEAR PARAMETERS
>  * /mavros/
> 
> PARAMETERS
>  * /mavros/cmd/use_comp_id_system_control: False
>  * /mavros/conn/heartbeat_rate: 1.0
>  * /mavros/conn/system_time_rate: 0.0
>  * /mavros/conn/timeout: 10.0
>  * /mavros/conn/timesync_rate: 0.0
>  * /mavros/fcu_url: udp://127.0.0.1:5...
>  * /mavros/gcs_url: udp://127.0.0.1@1...
>  * /mavros/global_position/frame_id: fcu
>  * /mavros/global_position/rot_covariance: 99999.0
>  * /mavros/global_position/tf/child_frame_id: fcu_utm
>  * /mavros/global_position/tf/frame_id: local_origin
>  * /mavros/global_position/tf/send: False
>  * /mavros/image/frame_id: px4flow
>  * /mavros/imu/angular_velocity_stdev: 0.000349065850399
>  * /mavros/imu/frame_id: fcu
>  * /mavros/imu/linear_acceleration_stdev: 0.0003
>  * /mavros/imu/magnetic_stdev: 0.0
>  * /mavros/imu/orientation_stdev: 1.0
>  * /mavros/local_position/frame_id: fcu
>  * /mavros/local_position/tf/child_frame_id: base_link
>  * /mavros/local_position/tf/frame_id: world
>  * /mavros/local_position/tf/send: True
>  * /mavros/mission/pull_after_gcs: True
>  * /mavros/mocap/use_pose: True
>  * /mavros/mocap/use_tf: False
>  * /mavros/plugin_blacklist: ['actuator_contro...
>  * /mavros/plugin_whitelist: []
>  * /mavros/px4flow/frame_id: px4flow
>  * /mavros/px4flow/ranger_fov: 0.0
>  * /mavros/px4flow/ranger_max_range: 5.0
>  * /mavros/px4flow/ranger_min_range: 0.3
>  * /mavros/safety_area/p1/x: 1.0
>  * /mavros/safety_area/p1/y: 1.0
>  * /mavros/safety_area/p1/z: 1.0
>  * /mavros/safety_area/p2/x: -1.0
>  * /mavros/safety_area/p2/y: -1.0
>  * /mavros/safety_area/p2/z: -1.0
>  * /mavros/setpoint_accel/send_force: False
>  * /mavros/setpoint_attitude/reverse_throttle: False
>  * /mavros/setpoint_attitude/tf/child_frame_id: attitude
>  * /mavros/setpoint_attitude/tf/frame_id: local_origin
>  * /mavros/setpoint_attitude/tf/listen: False
>  * /mavros/setpoint_attitude/tf/rate_limit: 10.0
>  * /mavros/setpoint_position/tf/child_frame_id: setpoint
>  * /mavros/setpoint_position/tf/frame_id: local_origin
>  * /mavros/setpoint_position/tf/listen: False
>  * /mavros/setpoint_position/tf/rate_limit: 50.0
>  * /mavros/startup_px4_usb_quirk: False
>  * /mavros/sys/disable_diag: False
>  * /mavros/sys/min_voltage: 10.0
>  * /mavros/target_component_id: 1
>  * /mavros/target_system_id: 1
>  * /mavros/tdr_radio/low_rssi: 40
>  * /mavros/time/time_ref_source: fcu
>  * /mavros/time/timesync_avg_alpha: 0.6
>  * /mavros/vibration/frame_id: vibration
>  * /mavros/vision_pose/tf/child_frame_id: vision
>  * /mavros/vision_pose/tf/frame_id: local_origin
>  * /mavros/vision_pose/tf/listen: False
>  * /mavros/vision_pose/tf/rate_limit: 10.0
>  * /mavros/vision_speed/listen_twist: False
>  * /robot_description: <?xml version="1....
>  * /rosdistro: indigo
>  * /rosversion: 1.11.20
>  * /tf_prefix: 
>  * /use_sim_time: True
> 
> NODES
>   /
>     gazebo (gazebo_ros/gzserver)
>     gazebo_gui (gazebo_ros/gzclient)
>     mavros (mavros/mavros_node)
>     spawn_erlecopter (gazebo_ros/spawn_model)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> core service [/rosout] found
> Taking off in in 7s
> process[mavros-1]: started with pid [641]
> [ INFO] [1554355518.249245223]: FCU URL: udp://127.0.0.1:5760@
> [ INFO] [1554355518.249463006]: udp0: Bind address: 127.0.0.1:5760
> [ INFO] [1554355518.249574731]: GCS URL: udp://127.0.0.1@127.0.0.1:14550
> [ INFO] [1554355518.249638660]: udp1: Bind address: 127.0.0.1:14555
> [ INFO] [1554355518.249685024]: udp1: Remote address: 127.0.0.1:14550
> [ INFO] [1554355518.288473239]: Plugin 3dr_radio loaded and initialized
> [ INFO] [1554355518.288516178]: Plugin actuator_control blacklisted
> [ INFO] [1554355518.288528105]: Plugin altitude blacklisted
> [ INFO] [1554355518.337454962]: Plugin cam_imu_sync loaded and initialized
> [ INFO] [1554355518.343459639]: Plugin command loaded and initialized
> [ INFO] [1554355518.343489420]: Plugin distance_sensor blacklisted
> [ INFO] [1554355518.343500343]: Plugin ftp blacklisted
> [ INFO] [1554355518.357003524]: Plugin global_position loaded and initialized
> [ INFO] [1554355518.357099950]: Plugin image_pub blacklisted
> [ INFO] [1554355518.366608114]: Plugin imu_pub loaded and initialized
> [ INFO] [1554355518.373478765]: Plugin local_position loaded and initialized
> [ INFO] [1554355518.374211261]: Plugin manual_control loaded and initialized
> [ INFO] [1554355518.374242254]: Plugin mocap_pose_estimate blacklisted
> [ INFO] [1554355518.377045458]: Plugin param loaded and initialized
> [ INFO] [1554355518.377071709]: Plugin px4flow blacklisted
> [ INFO] [1554355518.382834179]: Plugin rc_io loaded and initialized
> [ INFO] [1554355518.382874973]: Plugin safety_area blacklisted
> [ INFO] [1554355518.387554138]: Plugin setpoint_accel loaded and initialized
> [ INFO] [1554355518.387582674]: Plugin setpoint_attitude blacklisted
> [ INFO] [1554355518.395534883]: Plugin setpoint_position loaded and initialized
> [ INFO] [1554355518.408307968]: Plugin setpoint_raw loaded and initialized
> [ INFO] [1554355518.414679777]: Plugin setpoint_velocity loaded and initialized
> [ INFO] [1554355518.422357215]: Plugin sys_status loaded and initialized
> [ INFO] [1554355518.427603841]: Plugin sys_time loaded and initialized
> [ INFO] [1554355518.429169485]: Plugin vfr_hud loaded and initialized
> [ INFO] [1554355518.429239398]: Plugin vibration blacklisted
> [ INFO] [1554355518.430103422]: Plugin vision_pose_estimate blacklisted
> [ INFO] [1554355518.430129469]: Plugin vision_speed_estimate blacklisted
> [ INFO] [1554355518.437731457]: Plugin waypoint loaded and initialized
> [ INFO] [1554355518.437789760]: Built-in SIMD instructions: SSE, SSE2
> [ INFO] [1554355518.437803385]: Built-in MAVLink package version: 2016.5.20
> [ INFO] [1554355518.437814125]: Built-in MAVLink dialect: ardupilotmega
> [ INFO] [1554355518.437824419]: MAVROS started. MY ID 1.240, TARGET ID 1.1
> process[spawn_erlecopter-2]: started with pid [642]
> Taking off in in 6s
> spawn_model script started
> process[gazebo-3]: started with pid [857]
> [INFO] [WallTime: 1554355518.897111] [0.000000] Loading model xml from ros parameter
> [INFO] [WallTime: 1554355518.902594] [0.000000] Waiting for service /gazebo/spawn_urdf_model
> [ INFO] [1554355519.099669756]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1554355519.112393714]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
> process[gazebo_gui-4]: started with pid [871]
> [ INFO] [1554355519.439188153]: Model name:      erlecopter
> [ INFO] [1554355519.439223990]: Nb motor servos: 4
> [ INFO] [1554355519.462579971]: ARI: Services declared !
> [ INFO] [1554355519.462645022]: ARI: Binding to listening port from ArduPilot...
> 
> [ INFO] [1554355519.462685978]: ARI: SUCCESS in binding to port from ArduPilot
> 
> [ INFO] [1554355519.462727328]: ARI: Connecting send port to ArduPilot...
> 
> [ INFO] [1554355519.462759020]: ARI: Opened ArduPilot fdm socket
> 
> [ INFO] [1554355519.462801535]: ARI: Initialization finished
> [ INFO] [1554355519.462905371]: ARI: Starting listening loop for ArduPilot messages
> [INFO] [WallTime: 1554355519.510479] [0.000000] Calling service /gazebo/spawn_urdf_model
> [gazebo_gui-4] process has died [pid 871, exit code 1, cmd /usr/local/gym/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzclient __name:=gazebo_gui __log:=/root/.ros/log/06019c26-569a-11e9-a579-0242ac110003/gazebo_gui-4.log].
> log file: /root/.ros/log/06019c26-569a-11e9-a579-0242ac110003/gazebo_gui-4*.log
> Taking off in in 5s
> [ INFO] [1554355519.698108873]: Laser Plugin (robotNamespace = /), Info: Using the 'robotNamespace' param: '/'
> [ INFO] [1554355519.698150434]: Starting Laser Plugin (ns = /)!
> [ INFO] [1554355519.701875497]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
> [INFO] [WallTime: 1554355519.706095] [0.000000] Spawn status: SpawnModel: Successfully spawned model
> [spawn_erlecopter-2] process has finished cleanly
> log file: /root/.ros/log/06019c26-569a-11e9-a579-0242ac110003/spawn_erlecopter-2*.log
> Taking off in in 4s
> Taking off in in 3s
> Taking off in in 2s
> Taking off in in 1s
> Waiting for mavros...
>

**Comment by nzlz** [comment]
Im afraid we dont offer support for the previous version of gym-gazebo. Anyway, we have already solved this issue in gym-gazebo2, so checking the docker usage instructions might help you. You will just need to replicate our work in gymgazebo1.
