### ISSUE TITLE
gazebo_ros compilation error caused by conflicting protoc versions (carthographer_ros)

### ISSUE THREAD

**Issue by robotman801** [AcutronicRobotics/gym-gazebo2#13]
I am installing gym-gazebo2 following https://github.com/AcutronicRobotics/gym-gazebo2/blob/master/INSTALL.md. The configuration of the computer is Ubuntu 18.04 + ROS2 Crystal. However, it compiled fail when I use 'colcon build --merge-install --packages-skip individual_trajectories_bridge'. The main error is listed below. Could you please tell me where it is wrong? Thanks very much.

```bash
In file included from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:59:0,
                 from /usr/include/gazebo-9/gazebo/msgs/msgs.hh:35,
                 from /usr/include/gazebo-9/gazebo/sensors/Sensor.hh:33,
                 from /home/tony/ros2_mara_ws/src/gazebo_ros_pkgs/gazebo_ros/include/gazebo_ros/utils.hpp:20,
                 from /home/tony/ros2_mara_ws/src/gazebo_ros_pkgs/gazebo_ros/src/utils.cpp:15:
/usr/include/gazebo-9/gazebo/msgs/link_data.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/usr/include/gazebo-9/gazebo/msgs/link_data.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/usr/include/gazebo-9/gazebo/msgs/link_data.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~

In file included from /usr/include/ignition/msgs1/ignition/msgs/altimeter.pb.h:23:0,
                 from /usr/include/ignition/msgs1/ignition/msgs/MessageTypes.hh:31,
                 from /usr/include/ignition/msgs1/ignition/msgs/Utility.hh:29,
                 from /usr/include/ignition/msgs1/ignition/msgs.hh:25,
                 from /usr/include/ignition/transport4/ignition/transport/Node.hh:32,
                 from /usr/include/gazebo-9/gazebo/physics/Entity.hh:25,
                 from /home/tony/ros2_mara_ws/src/gazebo_ros_pkgs/gazebo_ros/src/gazebo_ros_state.cpp:16:
/usr/local/include/google/protobuf/arenastring.h:225:31: note: candidate: const string& google::protobuf::internal::ArenaStringPtr::GetNoArena() const
   inline const ::std::string& GetNoArena() const { return *ptr_; }
                               ^~~~~~~~~~
/usr/local/include/google/protobuf/arenastring.h:225:31: note:   candidate expects 0 arguments, 1 provided

/usr/local/include/google/protobuf/arenastring.h:225:31: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [CMakeFiles/gazebo_ros_state.dir/src/gazebo_ros_state.cpp.o] Error 1
make[1]: *** [CMakeFiles/gazebo_ros_state.dir/all] Error 2
make[2]: *** [CMakeFiles/gazebo_ros_properties.dir/src/gazebo_ros_properties.cpp.o] Error 1
make[1]: *** [CMakeFiles/gazebo_ros_properties.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< gazebo_ros	[ Exited with code 2 ]
                                   
Summary: 38 packages finished [36.6s]
  1 package failed: gazebo_ros
  1 package had stderr output: gazebo_ros
  5 packages not processed

```

**Comment by nzlz** [comment]
Seems like you have different versions of protobuf in your system, which is causing gazebo to have compilation issues. Did you install gazebo using the one lines installation? `curl -sSL http://get.gazebosim.org | sh
`.

Im pretty sure you have installed another version of protobuf via other packages, which overwrites system's protobuf. Check [this issue](https://bitbucket.org/osrf/gazebo/issues/2496/protobuf-error-on-ubuntu-1804) for instance. The solution is to get rid of the manually installed protobuf and try again.

**Comment by robotman801** [comment]
Hi, Nestor

I installed the gazebo following the one-liner installation instruction.
The issue should be caused by google-cartographer which I installed a few days ago, following https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html. The new version of protobuf is libprotoc 3.4.0. Do you know how to get rid of the manually installed protobuf? And which version of protobuf I should install? Thanks very much.

**Comment by nzlz** [comment]
I'm afraid I can't help much here. You should try the solutions to your problem various users posted in [this corthographer_ros issue](https://github.com/googlecartographer/cartographer_ros/issues/625). If not working, please comment the same problem you are having in that same issue or [open a new one](https://github.com/googlecartographer/cartographer_ros/issues).

**Comment by robotman801** [comment]
This issue is solved following this step. The method is tested on Ubuntu 18.04 + ROS2 Crytal

1.Delete the installed protobuf
   cd /usr/local/include/google
   sudo rm -rf protobuf
2.Recompile cartographer_ros
   The cartographer is installed following https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html. Before proceeding the step src/cartographer/scripts/install_proto3.sh, change the VERSION="v3.4.1" to VERSION="v3.0.0". Then do installation normally.

Now the cartographer-ros and gym-gazebo2 all works very well.

**Comment by nzlz** [comment]
Closing since not a strictly gym-gazebo2 related issue. Feel free to open a new issue if you encounter different problems.

**Comment by nzlz** [comment]
Did not read the comment where you solved the issue, thanks for sharing @robotman801 !!
