### ISSUE TITLE
Multi-agent simulation

### ISSUE THREAD

**Issue by ismorphism** [AcutronicRobotics/gym-gazebo2#15]
Hi, everyone,
Do you know ways how to simulate multiple robots here in your library or maybe you know other libraries to do it? Could you recommend something?

**Comment by nzlz** [comment]
Could you be more precise? What is what you want to achieve?

If you want to launch multiple simultaneous instances, yes its possible. We can provide more information if this is what you are looking for.

**Comment by ismorphism** [comment]
I have the following task -  there are 2 TurtleBots, map with obstacles and two target positions (1 robot - 1 target position). And I want to simulate this world with ability to use gym-like interface for design my MARL algorithms. This is exactly my goal.

**Comment by nzlz** [comment]
This is possible and has been done previously. You should be able to spawn and control both robots in gazebo using different namespaces.

Note that gym-gazebo2 is ROS2 focused and the gym-gazebo ROS (1) version was deprecated, so we don't offer support anymore. Im closing the issue for this reason, however you can post below if you have implementation specific questions.
