### ISSUE TITLE
gym-gazebo2 as TensorFlow agents

### ISSUE THREAD

**Issue by talregev** [AcutronicRobotics/gym-gazebo2#18]
**Please describe what is the problem you are trying to solve or the matter you want to discuss.**
Share your ideas here.

You can make gym-gazebo2 as part of TensorFlow agents and it will be more easy to use the latest reinforcement learning algorithms. 

https://github.com/tensorflow/agents

**Comment by nzlz** [comment]
Thanks for the input @talregev ,
We have discussed your proposal and have decided not going this path, at least for now. We will keep it in mind for the future anyway.
