### ISSUE TITLE
Can not run the example1

### ISSUE THREAD

**Issue by Abbyls** [AcutronicRobotics/gym-gazebo2#27]
Hi, I installed a new ubuntu18.04 system and installed the gym-gazebo2 by following the guidance. I did not see any problems during the installation process, but when I test the example1: 

> ~/gym-gazebo2/examples/MARA$ python3 gg_random.py -g

There is an error, and the gazebo shows up and then shutdown quickly. 

> [INFO] [launch]: process[gazebo-1]: started with pid [18661]
[INFO] [launch]: process[spawn_mara.py-2]: started with pid [18662]
[INFO] [launch]: process[hros_cognition_mara_components-3]: started with pid [18663]
[INFO] [launch]: process[mara_contact_publisher-4]: started with pid [18664]
[INFO] [launch]: process[spawn_mara.py-2]: process has finished cleanly
[ERROR] [launch]: process[gazebo-1] process has died [pid 18661, exit code 255, cmd 'gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/sha/gym-gazebo2/gym_gazebo2/worlds/empty__state_plugin__speed_up.world'].
^CTraceback (most recent call last):
  File "gg_random.py", line 16, in <module>
[WARNING] [launch.LaunchService]: user interrupted with ctrl-c (SIGINT)
    observation, reward, done, info = env.step(env.action_space.sample())
  File "/home/sha/gym-gazebo2/gym_gazebo2/envs/MARA/mara.py", line 308, in step
    obs = self.take_observation()
  File "/home/sha/gym-gazebo2/gym_gazebo2/envs/MARA/mara.py", line 235, in take_observation
    rclpy.spin_once(self.node)

I have installed ros2learn and there is a gym_gazebo2 package inside ros2learn package, which has the same problem to run the example1.
Do you know what is the problem?
Thanks in advance!

**Comment by nzlz** [comment]
Hi @Abbyls, 

We just updated our MARA repo to ROS2 Dashing, which has caused gym-gazebo2 to fail. We will fix this hopefully in the following hours.

In the meantime, you can try the instructions I left for another user [here](https://github.com/AcutronicRobotics/gym-gazebo2/issues/26#issuecomment-501113399) and see if it solves your issue.

**Comment by rkojcev** [comment]
@Abbyls  we are doing major refurbish and upgrade to all of our public repos these days in order to comply with different ros2 releases. Once we are done we will let you know and hopefully this will resolve all these inconsistencies trough out our repos.

**Comment by Abbyls** [comment]
@rkojcev @nzlz Thank you a lot! I have tried the suggestions in the question [https://github.com/AcutronicRobotics/gym-gazebo2/issues/26#issuecomment-501113399](url), but errors still there. I will wait for your good news!

**Comment by nzlz** [comment]
ROS2 Crystal version of gym-gazebo working again.

Created crystal branches for every gym-gazebo2 related repository. Go to the crystal branch of ros2learn or gym-gazebo2, depending what you want to install, and follow the distribution specific instructions available in the README.

We'll update the `master` (ROS2 Dashing compliant) branch the following days, stay tuned :)

**Comment by rkojcev** [comment]
@Abbyls can you please retry using the repo with the crystal branch and see if everything is working ok now?

**Comment by Abbyls** [comment]
@rkojcev Hi, I just tested the crystal branch （I deleted installed ros2learn, ros2_mara_ws, gym-gazebo2, and installed the crystal brach according to installation guidance. I also have used "git branch" to check if it is on the right branch). However, I got the same error as I posted after I run the example1:

> python3 gg_random.py -g -r -v 0.2
[INFO] [launch]: process[gazebo-1]: started with pid [19419]
[INFO] [launch]: process[spawn_mara.py-2]: started with pid [19420]
[INFO] [launch]: process[hros_cognition_mara_components-3]: started with pid [19421]
[INFO] [launch]: process[mara_contact_publisher-4]: started with pid [19422]
[INFO] [launch]: process[spawn_mara.py-2]: process has finished cleanly
[ERROR] [launch]: process[gazebo-1] process has died [pid 19419, exit code 255, cmd 'gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/sha/ros2learn/environments/gym-gazebo2/gym_gazebo2/worlds/empty__state_plugin.world'].

Gazebo just showed a second and shutdown.

**Comment by nzlz** [comment]
I just reinstalled gym-gazebo2 as you did and the command above works fine for me. Few things you could check:
- Which gazebo version are you using? We recommend the 9.9.0 you get currently from crystal debs (update if you dont have this one, https://github.com/AcutronicRobotics/gym-gazebo2/blob/crystal/INSTALL.md#dependent-tools).
- Is your bashrc clean/ pointing to the correct provisioning script? (https://github.com/AcutronicRobotics/gym-gazebo2/blob/crystal/INSTALL.md#provisioning)
- Is gazebo failing when you use `-r` flag? or it fails always? e.g `python3 gg_random.py -g`

**Comment by Abbyls** [comment]
Hi, thanks for your reply.

- I am using gazebo 9.0.0, which was installed along with ROS. And I found I can not update it to gazebo9.9.0 while ROS Crystal Debian packages (It only provide gazebo9.0 version). 

- The provisioning script has no problem.

- > python3 gg_random.py -r
has a problem, I need to check it further and will tell you the result.

**Comment by nzlz** [comment]
To get gazebo 9.9.0 you can try : ([official instructions](https://index.ros.org/doc/ros2/Installation/Crystal/Linux-Install-Debians/#setup-sources))

- To install the Debian packages you will need to add our Debian repository to your apt sources. First you will need to authorize our gpg key with apt like this:

```
sudo apt update && sudo apt install curl gnupg2 lsb-release
curl http://repo.ros2.org/repos.key | sudo apt-key add -
```

- And then add the repository to your sources list:
```
sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
```
- Update and install gazebo
```
apt-get update
apt-get install ros-dashing-gazebo*
```

**Comment by Abbyls** [comment]
Hi @nzlz, thank you a lot! Its the gazebo's problem, after I followed your guidance to install the gazebo, it works well. 

Before I updating the gazebo to 9.9.0, 
> python3 gg_random.py -r
works well, so I know the problem is on gazebo, but I don't know how to update it as every time I can only install gazebo9.0 by following the installation file. 

Thanks for all of you!

**Comment by Abbyls** [comment]
In addition, I got error: "no module named: gazebo_msgs" after I followed your guidance to install gazebo9.9.0. So, I installed some additional modules.

> sudo apt install ros-crystal-gazebo-msgs
> sudo apt install ros-crystal-gazebo-plugins

**Comment by nzlz** [comment]
Actually, I made a mistake telling you to install those **dashing** packages (updated the comment). I believe you followed crystal instructions, so please, install **crystal** version:

`apt-get install ros-crystal-gazebo*
`

Note that for dashing, `gazebo_ros_packages` needs to be installed from source at the moment.
