### ISSUE TITLE
gzclient not working

### ISSUE THREAD

**Issue by sulfur1c** [AcutronicRobotics/gym-gazebo2#31]
Hi,

I have installed ros2learn following README and INSTALL instructions from Crystall branch, examples are working fine but I can not see Gacebo working, I suppose it is disabled to train for having better performance, but I can not run it with gzclient command as it is explained in gym-gazebo2 README, I have got following error:
```bash
$ gzclient
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
gzclient: /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:630: virtual void Ogre::Node::setScale(const Ogre::Vector3&): Assertion `!inScale.isNaN() && "Invalid vector supplied as parameter"' failed.
Aborted (core dumped)
```

Could you advice? thanks in advance.

**Comment by sulfur1c** [comment]
Error log with verbose:

 gzclient --verbose
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.188.128
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/ament_index"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/colcon-core"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/doc"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/gripper_minimal_service"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/gripper_minimal_subscriber"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hans_modular_gazebo"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hans_t30_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hans_t49_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hans_t9_4_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hrim_actuator_gripper_msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hrim_actuator_gripper_srvs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hrim_actuator_rotaryservo_actions"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hrim_actuator_rotaryservo_msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hrim_actuator_rotaryservo_srvs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hrim_generic_msgs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hrim_generic_srvs"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/hros_cognition_mara_components"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_bringup"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_contact_publisher"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_gazebo"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_gazebo_plugins"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_minimal_publisher"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_minimal_subscriber"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_minimal_trajectory_action"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/mara_utils_scripts"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/orocos_kdl"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/python_orocos_kdl"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/robotiq_140_gripper_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/robotiq_85_gripper_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/robotiq_gazebo"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/robotiq_gripper_gazebo_plugins"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/robotiq_hande_gripper_description"
[Err] [InsertModelWidget.cc:405] Missing model.config for model "/home/sulfuric/ros2_mara_ws/install/share/urdfdom_py"
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
gzclient: /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:630: virtual void Ogre::Node::setScale(const Ogre::Vector3&): Assertion `!inScale.isNaN() && "Invalid vector supplied as parameter"' failed.
Aborted (core dumped)

**Comment by rkojcev** [comment]
Hi @sulfur1c, by looking at the output:

```
gzclient --verbose
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org
```

Gazebo 9.0 is known to be buggy and not compatible with certain internals we use for our environments. Can you please update to gazebo 9.9 and check if this solves your issue?

**Comment by alesolano** [comment]
If you want to stay with Gazebo 9.0.0 for now, you can solve this error finding all `radius="0"` and replacing them to `radius="0.01"`. Anyway, updating to Gazebo 9.9 is the best practice here.

**Comment by rkojcev** [comment]
@sulfur1c is this solving your issue?

**Comment by sulfur1c** [comment]
Hi @rkojcev,

Finally I have installed Gazebo 10 because it is easy to install through debian package following this instructions:

http://gazebosim.org/tutorials?tut=install_ubuntu#Alternativeinstallation:step-by-step

Just substitute Grazebo9 by Grazebo10

Thank you for your support.
