### ISSUE TITLE
I want to use Gym-Gazebo for drone training with ROS Kinetic + Gazebo 7. How can I set it up, using your previous repository?

### ISSUE THREAD

**Issue by wajeehulhassanvii** [AcutronicRobotics/gym-gazebo2#7]
It is to be used with Hectorquadrotor or Ardrone. Can you help me please?
Thanks

**Comment by nzlz** [comment]
Hi @wajeehulhassanvii ,

I'm afraid we are not supporting gym-gazebo1 anymore. If you would be interested in contributing to the current ROS2 based version we could give more feedback.

You might find inspiration in the erlecopter examples. Or make some research on this topic, there are even some papers published training drones in gym-gazebo.

Feel free contact me in private if you have **specific** questions.

**Comment by wajeehulhassanvii** [comment]
I'm sorry for the late reply @nzlz , Yes of course it would be great if I could contribute in anyway. Currently I've only started to learn it but hopefully I'll perfect the art. 
I already have a research topic for this semester, its a bit general like, 'controlling the drone using reinforcement learning in 3 dimension', if you have any idea then we can make it more specific.
If you can send me some paper regarding gym-gazebo that will be great.
Thank you very much @nzlz

**Comment by nzlz** [comment]
Take a look at the original gym-gazebo related articles, you might find some useful information there. 
https://scholar.google.com/scholar?cites=17520838235654758004&as_sdt=2005&sciodt=0,5&hl=es

Your goal or very similar has been already solved (improvable) using gym-gazebo and is perfectly feasible, but I'm afraid we have no time to support this kind of project. Again, if you have very specific questions contact me privately.

Regards,

**Comment by wajeehulhassanvii** [comment]
Sure, for the time its okay but I would stay in touch, if something interesting comes in my mind I would contact you regarding that.
Thanks for the help though :)
