### ISSUE TITLE
Do you have recommendation for use with ros1 or ros1/ros2 bridge?

### ISSUE THREAD

**Issue by rojas70** [AcutronicRobotics/gym-gazebo2#9]
For groups that have quite a bit of a code-base in ros1 and are not ready to move to ros2, can this package be a practical solution if used in conjunction with the ros1/2 bridge? Or any other arrangement?

**Comment by nzlz** [comment]
Hi @rojas70 ,

In gym-gazebo2 we make use of ROS2 specific implementations like the launch system, so it would be harder to replicate in a ROS1 scenario. But you can definitely create you own environments with your own launch system. I can give you instructions if you provide more details of your project.

If the robot you are using is a robotic arm, the examples available at [ROS2Learn](https://github.com/acutronicRobotics/ros2learn) should be valid too.

**Comment by rojas70** [comment]
@nzlz Thanks for the feedback!
We are working primarily with the baxter robot. What might be the main challenges in running with this system?

**Comment by nzlz** [comment]
Some difficulties that come to my mind are:
- How accurate is your ROS-gazebo simulation of this robot?
- Are your simulation drivers optimized enough for fast reinforcement learning?
- Launch system. You must substitute our launch system for a custom ROS1 launchfile execution. 

You might find many difficulties or just a few, can't say more without knowing the details. I would recommend to use the MARA of course, which is the robot for which we give **full support** in gym-gazebo2 and ROS2learn. You would probably save a lot of time fixing/improving things we have already solved.

Even if you decide to work with other robots we will be happy to assist you. Just notice that we don't have much bandwidth to support external projects.

**Comment by nzlz** [comment]
Feel free to reopen, closing for now.
